### ISSUE TITLE
OpenAI SDK traces will fail when `.with_raw_response` is used

### ISSUE THREAD

**Issue by tonybaloney** [pydantic/logfire#62]
### Description

I have this code:

```python
chat_completion_response = await openai_client.chat.completions.with_raw_response.create(
            messages=query_messages,  # type: ignore
            # Azure OpenAI takes the deployment name as the model name
            model=self.chatgpt_deployment if self.chatgpt_deployment else self.chatgpt_model,
            temperature=0.0,  # Minimize creativity for search query generation
            max_tokens=100,  # Setting too low risks malformed JSON, setting too high may affect performance
            n=1,
            tools=tools,
            tool_choice="auto",
        )
self.meter_ratelimit_remaining_tokens.set(
            int(chat_completion_response.headers.get("x-ratelimit-remaining-tokens", 0))
        )
self.meter_ratelimit_remaining_requests.set(
            int(chat_completion_response.headers.get("x-ratelimit-remaining-requests", 0))
        )
chat_completion = chat_completion_response.parse()
```

That causes a crash when instrumentation is enabled using logfire:

```default
ERROR:root:Exception while generating response stream: 'LegacyAPIResponse' object has no attribute 'choices'
Traceback (most recent call last):
  File "/Users/anthonyshaw/projects/azure-search-openai-demo/app/backend/app.py", line 181, in format_as_ndjson
    async for event in r:
  File "/Users/anthonyshaw/projects/azure-search-openai-demo/app/backend/approaches/chatapproach.py", line 152, in run_with_streaming
    extra_info, chat_coroutine = await self.run_until_final_call(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anthonyshaw/projects/azure-search-openai-demo/app/backend/approaches/chatreadretrieveread.py", line 140, in run_until_final_call
    chat_completion_response = await self.openai_client.chat.completions.with_raw_response.create(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anthonyshaw/projects/azure-search-openai-demo/.venv/lib/python3.11/site-packages/openai/_legacy_response.py", line 349, in wrapped
    return cast(LegacyAPIResponse[R], await func(*args, **kwargs))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anthonyshaw/projects/azure-search-openai-demo/.venv/lib/python3.11/site-packages/opentelemetry/instrumentation/openai/shared/chat_wrappers.py", line 128, in achat_wrapper
    response = await wrapped(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anthonyshaw/projects/azure-search-openai-demo/.venv/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 1334, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "/Users/anthonyshaw/projects/azure-search-openai-demo/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 1743, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anthonyshaw/projects/azure-search-openai-demo/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 1446, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/anthonyshaw/projects/azure-search-openai-demo/.venv/lib/python3.11/site-packages/logfire/_internal/integrations/openai.py", line 154, in instrumented_openai_request
    on_response(response, span)
  File "/Users/anthonyshaw/projects/azure-search-openai-demo/.venv/lib/python3.11/site-packages/logfire/_internal/integrations/openai.py", line 214, in on_chat_response
    'message': response.choices[0].message,
               ^^^^^^^^^^^^^^^^
AttributeError: 'LegacyAPIResponse' object has no attribute 'choices'
```

This looks to be because the instrumentation is wrapping the `.create()` function but assuming that the response is _always_ the pydantic model. When you call OpenAI SDK with `.with_raw_response` you get a LegacyAPIResponse object instead and you need to run `.parse()` on it. 

I'm doing `.with_raw_response` because I convert the rate-limiting headers into OpenTelemetry Metrics for the OTLP meters API.

### Python, Logfire & OS Versions, related packages

```TOML
logfire="0.28.0"
platform="macOS-13.6.6-x86_64-i386-64bit"
python="3.13.0a0 (heads/main:8ac2085b80, Sep 26 2023, 19:39:32) [Clang 14.0.3 (clang-1403.0.22.14.1)]"
[related_packages]
requests="2.31.0"
protobuf="4.25.3"
rich="13.7.1"
opentelemetry-api="1.24.0"
opentelemetry-exporter-otlp-proto-common="1.24.0"
opentelemetry-exporter-otlp-proto-http="1.24.0"
opentelemetry-instrumentation="0.45b0"
opentelemetry-proto="1.24.0"
opentelemetry-sdk="1.24.0"
opentelemetry-semantic-conventions="0.45b0"
```

**Comment by samuelcolvin** [comment]
ye, this is just a limitation/mistake in the OpenAI instrumentation, thanks for bringing it up, we'll fix soon.

**Comment by samuelcolvin** [comment]
Any chance this is fixed by #69?

**Comment by alexmojaki** [comment]
No, it's a different issue.

**Comment by samuelcolvin** [comment]
@Kludex is looking into this.
