### ISSUE TITLE
Error logging FastAPI arguments with async SQLAlchemy

### ISSUE THREAD

**Issue by WillDaSilva** [pydantic/logfire#66]
### Description

Full traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/logfire/_internal/integrations/fastapi.py", line 185, in solve_dependencies
    self.logfire_instance.log(level, 'FastAPI arguments', attributes=attributes)
  File "/usr/local/lib/python3.11/site-packages/logfire/_internal/main.py", line 547, in log
    if json_schema_properties := attributes_json_schema_properties(attributes):
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/logfire/_internal/json_schema.py", line 160, in attributes_json_schema_properties
    {key: create_json_schema(value, set()) for key, value in attributes.items() if key not in STACK_INFO_KEYS}
  File "/usr/local/lib/python3.11/site-packages/logfire/_internal/json_schema.py", line 160, in <dictcomp>
    {key: create_json_schema(value, set()) for key, value in attributes.items() if key not in STACK_INFO_KEYS}
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/logfire/_internal/json_schema.py", line 118, in create_json_schema
    return _mapping_schema(obj, seen)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/logfire/_internal/json_schema.py", line 212, in _mapping_schema
    **_properties({(k if isinstance(k, str) else safe_repr(k)): v for k, v in obj.items()}, seen),
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/logfire/_internal/json_schema.py", line 328, in _properties
    if (value_schema := create_json_schema(value, seen)) not in PLAIN_SCHEMAS:
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/logfire/_internal/json_schema.py", line 120, in create_json_schema
    return _dataclass_schema(obj, seen)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/logfire/_internal/json_schema.py", line 167, in _dataclass_schema
    return _custom_object_schema(obj, 'dataclass', (field.name for field in dataclasses.fields(obj)), seen)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/logfire/_internal/json_schema.py", line 342, in _custom_object_schema
    **_properties({key: getattr(obj, key) for key in keys}, seen),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/logfire/_internal/json_schema.py", line 342, in <dictcomp>
    **_properties({key: getattr(obj, key) for key in keys}, seen),
                        ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 566, in __get__
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
    value = self._fire_loader_callables(state, key, passive)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1121, in _fire_loader_callables
    return self.callable_(state, passive)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/strategies.py", line 967, in _load_for_state
    return self._emit_lazyload(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/strategies.py", line 1130, in _emit_lazyload
    result = session.execute(
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2306, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2191, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1850, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1990, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2360, in _handle_dbapi_exception
    raise exc_info[1].with_traceback(exc_info[2])
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 572, in execute
    self._adapt_connection.await_(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 122, in await_only
    raise exc.MissingGreenlet(
sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
```

This seems to occur whenever we call a FastAPI endpoint that uses a FastAPI dependency that returns a instance of one of our SQLAlchemy models. We use asyncio with SQLAlchemy, and have to load any relationships with `await instance.awaitable_attrs.attr`, since if we do IO otherwise we get the same sort of `sqlalchemy.exc.MissingGreenlet` error.

### Python, Logfire & OS Versions, related packages

```TOML
logfire="0.28.0"
platform="macOS-14.4.1-arm64-arm-64bit"
python="3.11.3 (main, Jun 29 2023, 17:08:14) [Clang 14.0.3 (clang-1403.0.22.14.1)]"
[related_packages]
requests="2.31.0"
pydantic="2.7.1"
fastapi="0.110.3"
protobuf="4.25.3"
rich="13.7.1"
opentelemetry-api="1.24.0"
opentelemetry-exporter-otlp-proto-common="1.24.0"
opentelemetry-exporter-otlp-proto-http="1.24.0"
opentelemetry-instrumentation="0.45b0"
opentelemetry-instrumentation-asgi="0.45b0"
opentelemetry-instrumentation-fastapi="0.45b0"
opentelemetry-proto="1.24.0"
opentelemetry-sdk="1.24.0"
opentelemetry-semantic-conventions="0.45b0"
opentelemetry-util-http="0.45b0"
```

**Comment by Kludex** [comment]
Can you provide us an MRE?

Showing how the dependency looks like, and the model, may help.

**Comment by alexmojaki** [comment]
Is your SQLAlchemy model class also a dataclass?

**Comment by WillDaSilva** [comment]
> Can you provide us a minimal, reproducible example?

@Kludex I'll try to put one together today.

> Is your SQLAlchemy model class also a dataclass?

@alexmojaki They use `DeclarativeBase` and `MappedAsDataclass`

**Comment by alexmojaki** [comment]
Looks like `dataclasses.is_dataclass` returns `True` for a `MappedAsDataclass`. So we just need our JSON encoder to check if something is a SQLAlchemy model before checking if it's a dataclass. This'll also be important outside of async to avoid DB queries.

**Comment by Kludex** [comment]
@WillDaSilva I've released 0.28.1. Can you confirm the issue is no longer present?

**Comment by WillDaSilva** [comment]
@Kludex I'll check now

**Comment by WillDaSilva** [comment]
@Kludex The same exception seems to be occurring:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/logfire/_internal/integrations/fastapi.py", line 185, in solve_dependencies
    self.logfire_instance.log(level, 'FastAPI arguments', attributes=attributes)
  File "/usr/local/lib/python3.11/site-packages/logfire/_internal/main.py", line 547, in log
    if json_schema_properties := attributes_json_schema_properties(attributes):
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/logfire/_internal/json_schema.py", line 160, in attributes_json_schema_properties
    {key: create_json_schema(value, set()) for key, value in attributes.items() if key not in STACK_INFO_KEYS}
  File "/usr/local/lib/python3.11/site-packages/logfire/_internal/json_schema.py", line 160, in <dictcomp>
    {key: create_json_schema(value, set()) for key, value in attributes.items() if key not in STACK_INFO_KEYS}
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/logfire/_internal/json_schema.py", line 118, in create_json_schema
    return _mapping_schema(obj, seen)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/logfire/_internal/json_schema.py", line 212, in _mapping_schema
    **_properties({(k if isinstance(k, str) else safe_repr(k)): v for k, v in obj.items()}, seen),
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/logfire/_internal/json_schema.py", line 328, in _properties
    if (value_schema := create_json_schema(value, seen)) not in PLAIN_SCHEMAS:
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/logfire/_internal/json_schema.py", line 120, in create_json_schema
    return _sqlalchemy_schema(obj, seen)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/logfire/_internal/json_schema.py", line 322, in _sqlalchemy_schema
    return _custom_object_schema(obj, 'sqlalchemy', sa_inspect(obj).attrs.keys(), seen)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/logfire/_internal/json_schema.py", line 342, in _custom_object_schema
    **_properties({key: getattr(obj, key) for key in keys}, seen),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/logfire/_internal/json_schema.py", line 342, in <dictcomp>
    **_properties({key: getattr(obj, key) for key in keys}, seen),
                        ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 566, in __get__
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
    value = self._fire_loader_callables(state, key, passive)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1121, in _fire_loader_callables
    return self.callable_(state, passive)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/strategies.py", line 967, in _load_for_state
    return self._emit_lazyload(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/strategies.py", line 1130, in _emit_lazyload
    result = session.execute(
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2306, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2191, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1850, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1990, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2360, in _handle_dbapi_exception
    raise exc_info[1].with_traceback(exc_info[2])
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 572, in execute
    self._adapt_connection.await_(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 122, in await_only
    raise exc.MissingGreenlet(
sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
```

**Comment by WillDaSilva** [comment]
I'm still working on the minimal reproducible example. I'll let you know when it is ready.

**Comment by alexmojaki** [comment]
This is progress. Now the JSON schema just needs to check for deferred attributes the same way the JSON encoder does.

**Comment by WillDaSilva** [comment]
I haven't been able to produce a minimal reproducible example yet, but I was able to get my code where the error is occurring to run with a breakpoint set within Logfire, which has let me debug this issue.

The error occurs because of the following line:
https://github.com/pydantic/logfire/blob/011e127e7e301ebc408f4c8068bb3e9ddbf63219/logfire/_internal/json_schema.py#L322

`sa_inspect(obj).attrs.keys()` will return a list of attributes names of `obj` that will be accessed within `_custom_object_schema`. The issue is that this list of attribute names includes SQLAlchemy relationships, which are typically lazy-loaded, thought the truth of how they're loaded in general is complicated: https://docs.sqlalchemy.org/en/20/orm/relationship_api.html

In my case, they cannot be lazy-loaded because they can only be loaded within an async context. Even if they could be lazy-loaded, I wouldn't want them to be because loading all relationships can be a very expensive operation. I think the solution here will be to filter down the list returned by `sa_inspect(obj).attrs.keys()` to only include non-relationship attribute names.

**Comment by WillDaSilva** [comment]
- https://github.com/pydantic/logfire/pull/73

I've tested out this change with my deployment that was previously seeing the `MissingGreenlet` error, and now that error does not occur. I'm open to other solutions as well - I just figured I'd share what works for me.

**Comment by WillDaSilva** [comment]
0.28.3 has fixed the issue. Thank you!
